### ISSUE TITLE
Move to TF 1.14 and 2.0

### ISSUE THREAD

**Issue by roman-kh** [analysiscenter/batchflow#365]
Replace all deprecated layers from `tf.layers` with `tf.keras.layers`

**Comment by roman-kh** [comment]
See #376 for 1.14

**Comment by SergeyTsimfer** [comment]
All of `tf.layers` are replaced with their `keras` counterparts; yet, importing `TFModel` still produces lots of warnings on some of `1.14.X` versions.

**Comment by roman-kh** [comment]
Are all of them `future deprecation` warnings?

**Comment by SergeyTsimfer** [comment]
Yes, and they can be ignored with 
```
import warnings
warnings.filterwarnings('ignore')
from tensorflow import logging
logging.set_verbosity(logging.ERROR)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
```
