### ISSUE TITLE
Add predefined SE-ResNet and SE-ResNeXt

### ISSUE THREAD

**Issue by roman-kh** [analysiscenter/batchflow#388]

**Comment by roman-kh** [comment]
@nikita-klsh - TF models
@Dimonovez - Torch models

**Comment by nikita-klsh** [comment]
It has already been implemented in TF models

**Comment by roman-kh** [comment]
So I can write `init_model('dynamic', SEResNet152)` and it will work, won't it?

**Comment by Dimonovez** [comment]
#438 Torch SEResNets
